image: barichello/godot-ci:3.3.2

variables:
  EXPORT_NAME: TowTrek
  ITCHIO_NAME: pulawskig/tow-trek

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/web
  - mkdir -v -p build/windows
  - mkdir -v -p build/linux
  - mkdir -v -p build/macos

web:
  stage: export
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web/

windows:
  stage: export
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows/

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

macosx:
  stage: export
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - godot -v --export "Mac OSX" ./build/macos/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/macos/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - web
  script:
    - rm -rf public
    - cp -r build/web public
  artifacts:
    paths:
      - public

itchio:
 stage: deploy
 rules:
    - if: $CI_COMMIT_BRANCH == "main"
 dependencies:
   - web
   - windows
   - linux
   - windows
 script:
   - butler push build/web $ITCHIO_NAME:web-stable
   - butler push build/windows $ITCHIO_NAME:windows-stable
   - butler push build/linux $ITCHIO_NAME:linux-stable
   - butler push build/macos $ITCHIO_NAME:macosx-stable
